### ISSUE TITLE
How Do I use this ?

### ISSUE THREAD

**Issue by rcuvier** [Dorian25/get-mangas#13]
How Do I use this ?

**Comment by Dorian25** [comment]
Hi,

Sorry, I really need to add a tutorial in my README.md ...

If you don't want to bother, you can download the executable [here](https://github.com/Dorian25/get-mangas/releases/tag/v1.1.0-alpha) 

Otherwise you can run the code with python from the App.py file (you will need the different libraries listed in the requirements.txt file)

**Comment by rcuvier** [comment]
I tried installing all the requirements and nothing :( 

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

python -m pip install -r requirements.txt
 nor 
python3 -m pip install -r requirements.txt

**Comment by Dorian25** [comment]
Yes indeed I forgot to put the requirements.txt file.
I will push some changes and the requirements.txt file

**Comment by Dorian25** [comment]
Now the file requirement.txt is [here](https://github.com/Dorian25/get-mangas/blob/master/requirements.txt)
